ALTER TABLE public.okrs ADD COLUMN IF NOT EXISTS okr_type TEXT DEFAULT 'personal';
ALTER TABLE public.okrs ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE public.okrs ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.okrs ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;