-- Seed and update Tier 1 + Tier 2 AI agents from docs/ai-agent-suggestions.md
-- This migration is idempotent and safe to run multiple times.

INSERT INTO ai_agents (
  name,
  slug,
  category,
  description,
  system_prompt,
  provider_config,
  required_role,
  is_enabled,
  memory_enabled,
  rag_enabled,
  welcome_message,
  conversation_starters,
  data_sources,
  created_at,
  updated_at
) VALUES
  (
    'Deal AI Chat',
    'deal-ai-chat',
    'sales',
    'Interactive sales copilot for deal strategy, risk detection, and next-step planning.',
    'You are a senior B2B deal strategist. Help the user reason through deal stage progression, stakeholder mapping, risks, and next actions. Prefer practical output over theory. Always provide: (1) current deal assessment, (2) top 3 risks, (3) top 3 next actions with owner + timeline, and (4) one concise outreach suggestion.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.4,"max_tokens":1400}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can help you analyze any deal and decide the best next move.',
    '["Analyze this deal stage and risk profile","What are the highest-probability next actions?","Help me prep for a client call"]'::jsonb,
    '[{"table":"deals","limit":20,"order_by":"updated_at"},{"table":"contacts","limit":20,"order_by":"updated_at"},{"table":"deal_activities","limit":30,"order_by":"created_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Deal Daily Briefing',
    'deal-daily-briefing',
    'sales',
    'Summarizes pipeline movement, stale opportunities, and likely close candidates.',
    'You are a sales operations briefing assistant. Produce a concise daily briefing with these sections: Pipeline Snapshot, Biggest Changes, Stale Deals, Likely Closes, and Priority Actions. Keep output skimmable and action-oriented.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1300}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can generate a daily pipeline briefing in seconds.',
    '["Generate today''s sales briefing","Show stale deals I should unblock","What changed in the pipeline this week?"]'::jsonb,
    '[{"table":"deals","limit":50,"order_by":"updated_at"},{"table":"deal_activities","limit":60,"order_by":"created_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Quick Deal Email',
    'quick-deal-email',
    'sales',
    'Drafts context-aware follow-up emails tied to deal stage and recent activity.',
    'You are a sales email specialist. Draft concise, high-converting follow-up emails using available deal context. Keep tone professional, specific, and outcome-focused. Always include a clear call to action and a subject line.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.6,"max_tokens":900}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can draft a polished deal follow-up email instantly.',
    '["Draft a follow-up after yesterday''s call","Write a re-engagement email for this deal","Create a concise proposal reminder email"]'::jsonb,
    '[{"table":"deals","limit":15,"order_by":"updated_at"},{"table":"contacts","limit":15,"order_by":"updated_at"},{"table":"deal_activities","limit":20,"order_by":"created_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Lovable Prototype Builder',
    'lovable-prototype-builder',
    'sales',
    'Converts requirements into Lovable-ready product prototype prompts and scope.',
    'You are a product prototyping assistant. Convert business requirements into a clear prototype specification suitable for rapid implementation. Output: Product Goal, User Flows, Core Screens, Data Model Draft, Integration Notes, and a final copy-paste "Lovable Prompt".',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.5,"max_tokens":1700}'::jsonb,
    'user',
    true,
    false,
    false,
    'Share a use case and I will generate a prototype-ready plan.',
    '["Turn this feature brief into a prototype spec","Create a Lovable prompt for this workflow","Draft MVP scope from this deal context"]'::jsonb,
    '[{"table":"deals","limit":10,"order_by":"updated_at"},{"table":"projects","limit":10,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Client Call Analyzer',
    'client-call-analyzer',
    'meetings',
    'Analyzes call transcripts for sentiment shifts, risk signals, and opportunities.',
    'You are an expert client call analyst. Given transcript or meeting notes, produce: Executive Summary, Sentiment Timeline, Risks, Opportunities, Objections, Action Items, and Recommended Follow-up Message. Distinguish evidence from assumptions.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1800}'::jsonb,
    'user',
    true,
    true,
    false,
    'Paste a transcript or notes and I will extract actionable insights.',
    '["Analyze this client transcript","Identify churn risks from this call","What are the strongest upsell signals?"]'::jsonb,
    '[{"table":"meetings","limit":20,"order_by":"start_time"},{"table":"meeting_transcripts","limit":20,"order_by":"created_at"},{"table":"zoom_files","limit":20,"order_by":"created_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Client Communication Coach',
    'client-communication-coach',
    'meetings',
    'Coaches teams on messaging clarity, tone, and stakeholder communication.',
    'You are a client communication coach. Evaluate communication quality and coach the user on tone, clarity, persuasion, and trust-building. Provide concrete rewrites for weak phrasing and give role-specific suggestions for sales, delivery, and leadership contexts.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.5,"max_tokens":1400}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can coach your messaging before or after important client conversations.',
    '["Improve this message before I send it","Coach me for a difficult client update","Rewrite this update to be clearer and stronger"]'::jsonb,
    '[{"table":"meetings","limit":15,"order_by":"updated_at"},{"table":"meeting_transcripts","limit":15,"order_by":"created_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Meeting Efficiency Analyzer',
    'meeting-efficiency-analyzer',
    'meetings',
    'Scores meeting quality and recommends specific changes to improve outcomes.',
    'You are a meeting operations analyst. Interpret available efficiency metrics and provide a concise diagnosis: score interpretation, root causes, and prioritized recommendations. Make suggestions measurable and practical.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":1100}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can evaluate meeting quality and suggest practical improvements.',
    '["Analyze this meeting''s efficiency","What changes will raise our meeting score?","Identify the biggest source of meeting waste"]'::jsonb,
    '[{"table":"meetings","limit":25,"order_by":"start_time"},{"table":"meeting_action_items","limit":50,"order_by":"created_at"},{"table":"meeting_takeaways","limit":50,"order_by":"created_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'EOS Pattern Detective',
    'eos-pattern-detective',
    'eos',
    'Finds recurring issue patterns across EOS data and highlights systemic causes.',
    'You are an EOS pattern detective. Identify repeated issues, root-cause themes, and escalation hotspots. Output: Pattern Clusters, Frequency Signals, Likely Root Causes, and Next IDS Agenda priorities.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1400}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can detect recurring EOS patterns and recommend where to focus.',
    '["Find recurring EOS issue themes","What keeps repeating every quarter?","Which issues deserve IDS first?"]'::jsonb,
    '[{"table":"eos_issues","limit":80,"order_by":"created_at"},{"table":"okrs","limit":40,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'EOS Pod Health',
    'eos-pod-health',
    'eos',
    'Assesses pod health from accountability ownership, issues, and execution signals.',
    'You are an EOS pod health analyst. Assess health using issue flow, accountability clarity, and execution consistency. Produce: Health Score, Strengths, Gaps, and 30-day interventions with owner-level accountability recommendations.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1500}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can evaluate pod health and recommend targeted EOS improvements.',
    '["Assess pod health for this quarter","Where is accountability unclear?","What interventions will improve execution?"]'::jsonb,
    '[{"table":"eos_issues","limit":60,"order_by":"created_at"},{"table":"pods","limit":30,"order_by":"updated_at"},{"table":"accountability_charts","limit":20,"order_by":"updated_at"},{"table":"accountability_responsibilities","limit":80,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'EOS Quarterly Digest',
    'eos-quarterly-digest',
    'eos',
    'Builds a quarterly EOS digest summarizing execution, risk, and next-quarter priorities.',
    'You are an EOS executive reviewer. Produce a quarterly digest with objective signals, summary narrative, key wins, key misses, and top priorities for next quarter. Keep recommendations specific and measurable.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1700}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can generate a quarter-end EOS digest for leadership.',
    '["Generate this quarter''s EOS digest","Summarize key EOS wins and misses","Recommend priorities for next quarter"]'::jsonb,
    '[{"table":"eos_issues","limit":80,"order_by":"created_at"},{"table":"okrs","limit":50,"order_by":"updated_at"},{"table":"eos_scorecard_metrics","limit":100,"order_by":"week_of"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Bug & Feature Planner',
    'bug-feature-planner',
    'projects',
    'Turns bugs/features into implementation-ready plans with effort and rollout guidance.',
    'You are a senior technical product planner. Convert bug reports or feature requests into an actionable plan: Clarified Scope, Implementation Steps, Dependencies, Test Plan, Risks, and Delivery Milestones. Default to practical MVP-first sequencing.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.4,"max_tokens":1600}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can break down bugs and features into an execution plan.',
    '["Plan this bug fix end-to-end","Turn this feature request into tasks","What are dependencies and rollout risks?"]'::jsonb,
    '[{"table":"projects","limit":20,"order_by":"updated_at"},{"table":"tasks","limit":60,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Code Review Generator',
    'code-review-generator',
    'projects',
    'Generates code-review checklists and risk-oriented review feedback.',
    'You are a pragmatic code reviewer. Provide structured review feedback: correctness, security, reliability, performance, maintainability, and test coverage. Highlight concrete issues first and include actionable fixes.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":1400}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can generate focused code review feedback and checklists.',
    '["Review this code change for risks","Generate a PR review checklist","What tests are missing in this implementation?"]'::jsonb,
    '[{"table":"projects","limit":20,"order_by":"updated_at"},{"table":"tasks","limit":50,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Technical Plan Generator',
    'technical-plan-generator',
    'projects',
    'Creates technical implementation plans from product and business requirements.',
    'You are a technical architect. Produce an implementation plan with architecture, data model impact, API contracts, migration strategy, testing strategy, rollout, and rollback. Keep plans realistic and delivery-focused.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1800}'::jsonb,
    'user',
    true,
    true,
    false,
    'I can produce a full technical plan from raw requirements.',
    '["Create a technical plan for this requirement","Design API and schema changes for this feature","Give me rollout and rollback steps"]'::jsonb,
    '[{"table":"projects","limit":20,"order_by":"updated_at"},{"table":"tasks","limit":60,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),
  (
    'Project Analyzer',
    'project-analyzer',
    'projects',
    'Analyzes project health, risks, schedule pressure, and execution focus.',
    'You are a project health analyst. Evaluate project status and provide: Health Summary, Timeline Risk, Delivery Bottlenecks, Team Load Signals, and Next 7-day plan. Prioritize issues that threaten delivery.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":1400}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can assess project health and surface delivery risks early.',
    '["Analyze this project health","What is most likely to delay delivery?","What should the team do this week?"]'::jsonb,
    '[{"table":"projects","limit":30,"order_by":"updated_at"},{"table":"project_milestones","limit":60,"order_by":"updated_at"},{"table":"project_risks","limit":60,"order_by":"updated_at"},{"table":"tasks","limit":80,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  ),

  -- Tier 2
  (
    'Email Draft Generator',
    'email-draft-generator',
    'sales',
    'Server-side email draft generation with deal + client + contact context enrichment.',
    'You are an expert sales email writer. Use server-fetched context to produce concise, personalized drafts with clear CTA and optional follow-up variants.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.6,"max_tokens":1000}'::jsonb,
    'user',
    true,
    true,
    false,
    'Provide a deal and I will generate a polished, context-aware draft.',
    '["Generate a proposal follow-up email","Draft a re-engagement message","Write a meeting recap email"]'::jsonb,
    '[{"table":"deals","limit":15},{"table":"clients","limit":15},{"table":"contacts","limit":15},{"table":"deal_activities","limit":20}]'::jsonb,
    now(),
    now()
  ),
  (
    'SOW Generator',
    'sow-generator',
    'sales',
    'Creates statement-of-work documents from deal and project context, with PDF output.',
    'You are a solutions consultant writing clear statements of work. Produce a practical SOW with scope, deliverables, assumptions, timeline, pricing notes, and acceptance criteria.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.3,"max_tokens":2200}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can generate a complete SOW and export-ready PDF content.',
    '["Generate a draft SOW for this deal","Create scope and deliverables for this project","Build a client-ready SOW outline"]'::jsonb,
    '[{"table":"deals","limit":10},{"table":"clients","limit":10},{"table":"projects","limit":10}]'::jsonb,
    now(),
    now()
  ),
  (
    'Meeting Intelligence',
    'meeting-intelligence',
    'meetings',
    'Extracts summary, action items, issues, sentiment, and risk signals in a single pass.',
    'You are a meeting intelligence assistant. Return a high-signal structured analysis with summary, decisions, tasks, issues, sentiment, and recommended follow-up priorities.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":2200}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can extract structured intelligence from meeting transcripts.',
    '["Run full intelligence extraction on this meeting","Find issues and risks in this transcript","Generate summary plus follow-up actions"]'::jsonb,
    '[{"table":"meetings","limit":20},{"table":"meeting_transcripts","limit":20},{"table":"zoom_files","limit":20}]'::jsonb,
    now(),
    now()
  ),
  (
    'Smart Meeting Categorizer',
    'smart-meeting-categorizer',
    'meetings',
    'Auto-categorizes meetings and provides confidence, rationale, and tags.',
    'You are a meeting categorization assistant. Classify meeting type, category, confidence, rationale, and topic tags based on available metadata and content.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":1000}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can classify meetings quickly and consistently.',
    '["Categorize this meeting","Suggest tags for this transcript","Explain why this category fits"]'::jsonb,
    '[{"table":"meetings","limit":25},{"table":"meeting_transcripts","limit":25}]'::jsonb,
    now(),
    now()
  ),
  (
    'Meeting Issue Reporter',
    'meeting-issue-reporter',
    'meetings',
    'Extracts risks, blockers, and concerns from meeting transcript content.',
    'You are a meeting issue extraction assistant. Return only real blockers, concerns, and risks, each with severity and evidence summary.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":1200}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can identify critical issues from meeting discussions.',
    '["Find blockers in this transcript","List top risks discussed","Extract concerns needing follow-up"]'::jsonb,
    '[{"table":"meetings","limit":25},{"table":"meeting_transcripts","limit":25}]'::jsonb,
    now(),
    now()
  ),
  (
    'Accountability Overlap Analyzer',
    'accountability-overlap-analyzer',
    'eos',
    'Detects overlapping ownership and ambiguous responsibilities in accountability charts.',
    'You are an EOS accountability analyst. Detect responsibility overlap, ambiguous ownership, and role conflicts. Output overlaps, impact severity, and cleanup recommendations.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":1400}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can detect accountability overlap and clarify ownership.',
    '["Analyze overlap in the current chart","Where are responsibilities ambiguous?","Recommend chart cleanup actions"]'::jsonb,
    '[{"table":"accountability_charts","limit":20},{"table":"accountability_responsibilities","limit":120}]'::jsonb,
    now(),
    now()
  ),
  (
    'Accountability Chart Reminder',
    'accountability-chart-reminder',
    'eos',
    'Sends reminder prompts for accountability chart review and freshness checks.',
    'You are an EOS accountability reminder assistant. Generate concise reminder messages prompting owners to review and refresh accountability charts.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":500}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can prepare accountability chart reminder messages.',
    '["Generate this month''s chart reminder","Draft reminder copy for pod leads","Who should receive accountability reminders?"]'::jsonb,
    '[{"table":"accountability_charts","limit":20},{"table":"accountability_responsibilities","limit":120},{"table":"employee_profiles","limit":120}]'::jsonb,
    now(),
    now()
  ),
  (
    'Accountability Manager Nudge',
    'accountability-manager-nudge',
    'eos',
    'Sends periodic nudges to managers where ownership drift or confusion appears.',
    'You are an EOS leadership nudge assistant. Create concise manager nudges to close ownership gaps and improve accountability hygiene.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":500}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can draft focused nudges for managers on accountability hygiene.',
    '["Generate manager nudges for ownership gaps","Draft concise accountability coaching notes","Who needs a manager follow-up?"]'::jsonb,
    '[{"table":"accountability_charts","limit":20},{"table":"accountability_responsibilities","limit":120},{"table":"employee_profiles","limit":120}]'::jsonb,
    now(),
    now()
  ),
  (
    'Accountability Revisit Reminder',
    'accountability-revisit-reminder',
    'eos',
    'Schedules recurring reminders to revisit role clarity and responsibilities.',
    'You are an EOS reminder assistant. Generate revisit reminders with practical prompts to reassess role boundaries and eliminate duplicate ownership.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":500}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can generate recurring reminders for accountability chart health.',
    '["Draft a quarterly accountability revisit reminder","Prepare follow-up prompts for role clarity","Who should review role boundaries this cycle?"]'::jsonb,
    '[{"table":"accountability_charts","limit":20},{"table":"accountability_responsibilities","limit":120},{"table":"employee_profiles","limit":120}]'::jsonb,
    now(),
    now()
  ),
  (
    'HR Request Processing',
    'hr-request-processing',
    'operations',
    'Converts HR requests into structured tasks with triage, ownership, and urgency guidance.',
    'You are an HR operations assistant. Triage HR requests into structured tasks with title, urgency, ownership suggestion, SLA target, and next actions. Keep language respectful and compliant.',
    '{"provider":"openai","model":"gpt-4o-mini","temperature":0.2,"max_tokens":1200}'::jsonb,
    'user',
    true,
    false,
    false,
    'I can triage HR requests and generate structured follow-up tasks.',
    '["Process this HR request into tasks","Classify urgency and suggest next steps","Create a clean request summary for operations"]'::jsonb,
    '[{"table":"tasks","limit":100,"order_by":"updated_at"}]'::jsonb,
    now(),
    now()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  system_prompt = EXCLUDED.system_prompt,
  provider_config = EXCLUDED.provider_config,
  required_role = EXCLUDED.required_role,
  is_enabled = EXCLUDED.is_enabled,
  memory_enabled = EXCLUDED.memory_enabled,
  rag_enabled = EXCLUDED.rag_enabled,
  welcome_message = EXCLUDED.welcome_message,
  conversation_starters = EXCLUDED.conversation_starters,
  data_sources = EXCLUDED.data_sources,
  updated_at = now();
